# Hologram will run from same directory where this config file resides
# All paths should be relative to there

# The directory containing the source files to parse recursively
source: ./less

# The directory that hologram will build to
destination: ../doc/doc

# Hologram theme
documentation_assets: ./vendors/Cortana
custom_markdown: ./vendors/Cortana/CortanaMarkdownRenderer.rb

# To have a custom index page build with your README.md
index: README.md

# List all css to include for the styleguide render examples (path from styleguide directory)
css_include:
  - '../../dev/css/style.css'

  # List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - 'http://code.jquery.com/jquery-1.10.2.min.js'
  - '../../dev/js/script.js'


# String who is used to split the category name and create category wrapper
name_scope: ' - '
